# Generated by Django 3.2.9 on 2021-11-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Switch', 'switch'), ('Air Conditioner', 'a/c'), ('Water Heater', 'water_heater')], max_length=50)),
                ('webhook_url', models.URLField(max_length=255)),
            ],
        ),
    ]
