# Generated by Django 3.2.9 on 2021-11-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('Air Conditioner', 'a/c'), ('Switch', 'switch'), ('Water Heater', 'water_heater')], max_length=50),
        ),
    ]
