# Generated by Django 3.2.9 on 2021-11-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('a/c', 'Air Conditioner'), ('switch', 'Switch'), ('water_heater', 'Water Heater')], max_length=50),
        ),
    ]
