# Generated by Django 3.2.9 on 2021-11-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='data',
            field=models.JSONField(default={}, null=True, verbose_name='ContactInfo'),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('a/c', 'Air Conditioner'), ('switch', 'Switch'), ('water_heater', 'Water Heater'), ('controller', 'controller')], max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='webhook_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
