# Generated by Django 3.2.9 on 2021-11-07 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20211106_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='data',
            new_name='state',
        ),
    ]
